line_length:
  warning: 100
  error: 100

file_length:
  warning: 450
  error: 450

identifier_name:
  min_length:
    warning: 1
    error: 1

trailing_comma:
  mandatory_comma: false

type_body_length:
  warning: 150
  error: 200

function_body_length:
  warning: 40
  error: 60
